Costy btanch
Elenaadochitei/BarieraJava pull request #6
Opened 2020-09-24 21:06 UTC by costy619

2020-09-28 06:02 UTC, Elenaadochitei approved these changes

2020-09-29 08:23 UTC, ionutvacariu requested changes

2020-09-29 08:23 UTC, ionutvacariu commented on src/main/java/com/example/demo/ControllerBariera.java
> +    public DetaliiBariera postNewUser(@PathVariable("id") String id,@RequestBody DetaliiBariera detaliiBarieraList) throws Exception {
please format code here

2020-09-29 08:23 UTC, ionutvacariu commented on src/main/java/com/example/demo/ControllerBariera.java
>          log.logOn(isActive);
why use logon ? return LoginInfo from getConfirmation()

2020-09-30 06:37 UTC, Elenaadochitei commented on src/main/java/com/example/demo/ConnectLogInData.java
>              sql = "SELECT id, username, pass FROM USERS where username='"+username+"' and pass='"+pass+"'";
why do you use sql injection?

2020-09-30 08:31 UTC, Elenaadochitei commented on src/main/java/com/example/demo/ConnectLogInData.java
> +            sql = "SELECT id, username, pass FROM USERS where username='"+username+"' and pass='"+pass+"'";
The code is vulnerable to SQL injections.

2020-10-01 17:47 UTC, closed without merging